# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vegemite Soup
email: CaledoniaThomson@gmail.com
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vegemitesoup.com" # the base hostname & protocol for your site
twitter_username: calrthom
github_username:  calthomson
instagram_username: calrthom

# Build settings
markdown: kramdown

collections:
  inbetween:
    output: true

excerpt_separator: "<!--excerpt-->"

gems: ["jekyll-paginate"]
paginate: 10