title: Vegemite Soup
email: CaledoniaThomson@gmail.com
description: A blog about things
url: "http://vegemitesoup.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog

# Comments
discus_identifier: mr-brown
